"use client";

import { useState, useMemo } from "react";
import {
  ProductionGoldResult,
  GoldMetricCategory,
  CATEGORY_LABELS,
  GoldTransformSpec,
  GoldKPISpec,
  AggregationConfig,
  BusinessMetricValidation,
  ExecutiveView,
  GoldDataQualityMonitor,
  GoldAuditEntry,
  DependencyValidation,
  GoldPerformanceRec,
  ThresholdAlert,
  GoldReconciliation,
  GovernanceConfig,
  DependencyNode,
  DependencyLink,
  analyzeProductionGold,
} from "@/lib/gold-layer-analyzer";

interface Props {
  open: boolean;
  onClose: () => void;
  sourceCode: string;
  outputCode: string;
  direction: "aws-to-azure" | "azure-to-aws";
}

const CAT_COLORS: Record<GoldMetricCategory, string> = {
  "kpi-calculation": "#f59e0b",
  "business-metric": "#3b82f6",
  "aggregation": "#8b5cf6",
  "compliance-metric": "#ef4444",
  "asset-lifecycle": "#10b981",
  "security-posture": "#f97316",
  "reporting-dataset": "#06b6d4",
};

const CAT_ICONS: Record<GoldMetricCategory, string> = {
  "kpi-calculation": "📊",
  "business-metric": "💼",
  "aggregation": "∑",
  "compliance-metric": "🛡",
  "asset-lifecycle": "⟳",
  "security-posture": "🔒",
  "reporting-dataset": "📋",
};

type TabId = "summary" | "kpis" | "aggregations" | "specs" | "pipeline" | "executive" | "validation" | "audit" | "dq-monitoring" | "dependencies" | "performance" | "schema" | "alerts" | "reconciliation" | "governance";

export default function GoldLayerPanel({ open, onClose, sourceCode, outputCode, direction }: Props) {
  const [activeTab, setActiveTab] = useState<TabId>("summary");
  const [expandedSpec, setExpandedSpec] = useState<string | null>(null);
  const [copiedId, setCopiedId] = useState<string | null>(null);
  const [filterCat, setFilterCat] = useState<GoldMetricCategory | "all">("all");

  const result = useMemo<ProductionGoldResult | null>(() => {
    if (!open || !sourceCode) return null;
    try {
      return analyzeProductionGold(sourceCode, outputCode, direction);
    } catch {
      return null;
    }
  }, [open, sourceCode, outputCode, direction]);

  if (!open) return null;

  const copyCode = (code: string, id: string) => {
    navigator.clipboard.writeText(code);
    setCopiedId(id);
    setTimeout(() => setCopiedId(null), 2000);
  };

  const downloadAll = () => {
    if (!result) return;
    const sections: string[] = [];

    sections.push("-- ════════════════════════════════════════════════════════════════");
    sections.push("-- GOLD LAYER PRODUCTION ANALYTICS PIPELINE");
    sections.push("-- Generated by FlowMigrate Enterprise");
    sections.push("-- ════════════════════════════════════════════════════════════════\n");

    sections.push("-- ═══ KPI SPECIFICATIONS ═══");
    result.kpis.forEach((k) => sections.push(`-- KPI: ${k.name} (${k.category})\n${k.code}\n`));

    sections.push("\n-- ═══ AGGREGATION FRAMEWORK ═══");
    result.aggregationFramework.forEach((a) => sections.push(`-- Aggregation: ${a.name}\n${a.code}\n`));

    sections.push("\n-- ═══ ANALYTICS PIPELINE ═══");
    result.specs.forEach((s) => sections.push(`-- ${s.name} — ${s.description}\n${s.code}\n`));

    sections.push("\n-- ═══ EXECUTIVE VIEWS ═══");
    result.executiveViews.forEach((v) => sections.push(`-- View: ${v.name}\n${v.code}\n`));

    sections.push("\n-- ═══ METRIC VALIDATIONS ═══");
    result.metricValidations.forEach((v) => sections.push(`-- Validation: ${v.metricName}\n${v.code}\n`));

    sections.push("\n-- ═══ DATA QUALITY MONITORS ═══");
    result.dataQualityMonitors.forEach((m) => sections.push(`-- Monitor: ${m.name}\n${m.code}\n`));

    sections.push("\n-- ═══ AUDIT FRAMEWORK ═══");
    result.auditFramework.forEach((a) => sections.push(`-- Audit: ${a.name}\n${a.code}\n`));

    sections.push("\n-- ═══ DEPENDENCY VALIDATIONS ═══");
    result.dependencyValidations.forEach((d) => sections.push(`-- Dep: ${d.name}\n${d.code}\n`));

    sections.push("\n-- ═══ PERFORMANCE OPTIMIZATIONS ═══");
    result.performanceRecs.forEach((p) => sections.push(`-- Perf: ${p.title}\n${p.code}\n`));

    sections.push("\n-- ═══ PRODUCTION PIPELINE ORCHESTRATOR ═══");
    result.productionPipeline.forEach((p) => sections.push(`-- ${p.stage}\n${p.code}\n`));

    const blob = new Blob([sections.join("\n")], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `gold_production_pipeline_${Date.now()}.sql`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const tabs: { id: TabId; label: string; count?: number }[] = [
    { id: "summary", label: "Summary" },
    { id: "kpis", label: "KPIs", count: result?.kpis.length },
    { id: "aggregations", label: "Aggregations", count: result?.aggregationFramework.length },
    { id: "specs", label: "Analytics Pipeline", count: result?.specs.length },
    { id: "pipeline", label: "Production Pipeline", count: result?.productionPipeline.length },
    { id: "executive", label: "Executive Views", count: result?.executiveViews.length },
    { id: "validation", label: "Validation & DQ", count: (result?.metricValidations.length || 0) + (result?.dataQualityMonitors.length || 0) },
    { id: "audit", label: "Audit & Deps", count: (result?.auditFramework.length || 0) + (result?.dependencyValidations.length || 0) },
    { id: "performance", label: "Performance", count: result?.performanceRecs.length },
    { id: "dependencies", label: "Dependency Graph", count: result?.dependencyGraph.nodes.length },
    { id: "schema", label: "Output Schema", count: result?.summary.totalOutputFields },
    { id: "alerts", label: "Threshold Alerts", count: result?.thresholdAlerts.length },
    { id: "reconciliation", label: "Reconciliation", count: result?.goldReconciliation.length },
    { id: "governance", label: "Governance", count: result?.governance.length },
  ];

  const confColor = (c: number) => c >= 0.8 ? "#10b981" : c >= 0.6 ? "#f59e0b" : "#ef4444";

  return (
    <div style={{ position: "fixed", inset: 0, zIndex: 9999, display: "flex", alignItems: "center", justifyContent: "center", background: "rgba(0,0,0,0.6)", backdropFilter: "blur(4px)" }}>
      <div style={{ width: "96vw", maxWidth: 1500, height: "92vh", background: "#0f1117", borderRadius: 16, border: "1px solid #1e293b", display: "flex", flexDirection: "column", overflow: "hidden" }}>

        {/* Header */}
        <div style={{ padding: "20px 28px", borderBottom: "1px solid #1e293b", display: "flex", alignItems: "center", justifyContent: "space-between" }}>
          <div style={{ display: "flex", alignItems: "center", gap: 14 }}>
            <div style={{ width: 42, height: 42, borderRadius: 10, background: "linear-gradient(135deg, #f59e0b, #f97316)", display: "flex", alignItems: "center", justifyContent: "center", fontSize: 20 }}>◆</div>
            <div>
              <h2 style={{ margin: 0, fontSize: 18, fontWeight: 700, color: "#f1f5f9" }}>Production Gold Analytics Layer</h2>
              <p style={{ margin: 0, fontSize: 12, color: "#64748b" }}>KPIs | Aggregation Framework | Executive Views | Data Quality | Audit | Performance Optimization</p>
            </div>
          </div>
          <div style={{ display: "flex", alignItems: "center", gap: 12 }}>
            {result && (
              <>
                <div style={{ display: "flex", gap: 8 }}>
                  <StatBadge label="KPIs" value={result.kpis.length} color="#f59e0b" />
                  <StatBadge label="Views" value={result.executiveViews.length} color="#3b82f6" />
                  <StatBadge label="Monitors" value={result.dataQualityMonitors.length} color="#8b5cf6" />
                  <StatBadge label="Stages" value={result.productionPipeline.length} color="#10b981" />
                </div>
                <div style={{ padding: "6px 14px", borderRadius: 20, fontSize: 13, fontWeight: 600, background: `${confColor(result.overallConfidence)}18`, color: confColor(result.overallConfidence), border: `1px solid ${confColor(result.overallConfidence)}40` }}>
                  {Math.round(result.overallConfidence * 100)}%
                </div>
                <button onClick={downloadAll} style={{ padding: "6px 14px", borderRadius: 8, background: "#f59e0b", color: "#000", border: "none", cursor: "pointer", fontSize: 13, fontWeight: 700 }}>Download All</button>
              </>
            )}
            <button onClick={onClose} style={{ width: 32, height: 32, borderRadius: 8, background: "#1e293b", color: "#94a3b8", border: "none", cursor: "pointer", fontSize: 18 }}>✕</button>
          </div>
        </div>

        {/* Tabs — scrollable */}
        <div style={{ display: "flex", gap: 2, padding: "0 28px", borderBottom: "1px solid #1e293b", background: "#0a0d14", overflowX: "auto", flexShrink: 0 }}>
          {tabs.map((t) => (
            <button key={t.id} onClick={() => setActiveTab(t.id)} style={{
              padding: "12px 16px", background: "transparent", border: "none", whiteSpace: "nowrap",
              borderBottom: activeTab === t.id ? "2px solid #f59e0b" : "2px solid transparent",
              color: activeTab === t.id ? "#f59e0b" : "#64748b",
              cursor: "pointer", fontSize: 12, fontWeight: 600, display: "flex", alignItems: "center", gap: 5, transition: "all 0.15s",
            }}>
              {t.label}
              {t.count !== undefined && <span style={{ padding: "1px 6px", borderRadius: 10, background: activeTab === t.id ? "#f59e0b18" : "#1e293b", fontSize: 10 }}>{t.count}</span>}
            </button>
          ))}
        </div>

        {/* Content */}
        <div style={{ flex: 1, overflow: "auto", padding: 28 }}>
          {!result ? (
            <div style={{ textAlign: "center", color: "#64748b", padding: 60, fontSize: 14 }}>Paste source workflow code to analyze Gold layer analytics</div>
          ) : activeTab === "summary" ? (
            <SummaryTab result={result} />
          ) : activeTab === "kpis" ? (
            <KPIsTab kpis={result.kpis} copiedId={copiedId} onCopy={copyCode} expanded={expandedSpec} onToggle={(id) => setExpandedSpec(expandedSpec === id ? null : id)} />
          ) : activeTab === "aggregations" ? (
            <AggregationsTab configs={result.aggregationFramework} copiedId={copiedId} onCopy={copyCode} expanded={expandedSpec} onToggle={(id) => setExpandedSpec(expandedSpec === id ? null : id)} />
          ) : activeTab === "specs" ? (
            <SpecsTab specs={result.specs} expanded={expandedSpec} onToggle={(id) => setExpandedSpec(expandedSpec === id ? null : id)} copiedId={copiedId} onCopy={copyCode} filterCat={filterCat} onFilter={setFilterCat} />
          ) : activeTab === "pipeline" ? (
            <PipelineTab stages={result.productionPipeline} copiedId={copiedId} onCopy={copyCode} expanded={expandedSpec} onToggle={(id) => setExpandedSpec(expandedSpec === id ? null : id)} />
          ) : activeTab === "executive" ? (
            <ExecutiveViewsTab views={result.executiveViews} copiedId={copiedId} onCopy={copyCode} expanded={expandedSpec} onToggle={(id) => setExpandedSpec(expandedSpec === id ? null : id)} />
          ) : activeTab === "validation" ? (
            <ValidationDQTab validations={result.metricValidations} monitors={result.dataQualityMonitors} copiedId={copiedId} onCopy={copyCode} expanded={expandedSpec} onToggle={(id) => setExpandedSpec(expandedSpec === id ? null : id)} />
          ) : activeTab === "audit" ? (
            <AuditDepsTab audit={result.auditFramework} deps={result.dependencyValidations} incrementalConfig={result.incrementalConfig} copiedId={copiedId} onCopy={copyCode} expanded={expandedSpec} onToggle={(id) => setExpandedSpec(expandedSpec === id ? null : id)} />
          ) : activeTab === "performance" ? (
            <PerformanceTab recs={result.performanceRecs} copiedId={copiedId} onCopy={copyCode} expanded={expandedSpec} onToggle={(id) => setExpandedSpec(expandedSpec === id ? null : id)} />
          ) : activeTab === "dependencies" ? (
            <DependencyTab graph={result.dependencyGraph} />
          ) : activeTab === "alerts" ? (
            <AlertsTab alerts={result.thresholdAlerts} copiedId={copiedId} onCopy={copyCode} />
          ) : activeTab === "reconciliation" ? (
            <ReconciliationTab recons={result.goldReconciliation} copiedId={copiedId} onCopy={copyCode} />
          ) : activeTab === "governance" ? (
            <GovernanceTab configs={result.governance} copiedId={copiedId} onCopy={copyCode} />
          ) : (
            <SchemaTab specs={result.specs} />
          )}
        </div>
      </div>
    </div>
  );
}

/* ═══════════════════════════════════════════════════════════════════════════
   HELPER COMPONENTS
   ═══════════════════════════════════════════════════════════════════════════ */

function StatBadge({ label, value, color }: { label: string; value: number; color: string }) {
  return (
    <div style={{ padding: "4px 10px", borderRadius: 6, background: `${color}12`, border: `1px solid ${color}30`, display: "flex", alignItems: "center", gap: 5 }}>
      <span style={{ fontSize: 14, fontWeight: 800, color }}>{value}</span>
      <span style={{ fontSize: 10, color: "#94a3b8", fontWeight: 600 }}>{label}</span>
    </div>
  );
}

function CodeBlock({ code, id, copiedId, onCopy, accent = "#fbbf24" }: { code: string; id: string; copiedId: string | null; onCopy: (code: string, id: string) => void; accent?: string }) {
  return (
    <div style={{ borderTop: "1px solid #1e293b" }}>
      <div style={{ display: "flex", justifyContent: "flex-end", padding: "8px 16px 0", gap: 8 }}>
        <button onClick={() => onCopy(code, id)} style={{ padding: "4px 12px", borderRadius: 6, background: "#1e293b", color: copiedId === id ? "#10b981" : "#94a3b8", border: "none", cursor: "pointer", fontSize: 12, fontWeight: 600 }}>
          {copiedId === id ? "Copied!" : "Copy"}
        </button>
      </div>
      <pre style={{ margin: 0, padding: "12px 20px 20px", fontSize: 11.5, lineHeight: 1.6, color: accent, overflow: "auto", fontFamily: "'JetBrains Mono', 'Fira Code', monospace", maxHeight: 500 }}>
        {code}
      </pre>
    </div>
  );
}

function SeverityBadge({ severity }: { severity: string }) {
  const colors: Record<string, string> = { critical: "#ef4444", high: "#f97316", error: "#ef4444", medium: "#f59e0b", warning: "#f59e0b", low: "#3b82f6", info: "#06b6d4" };
  const color = colors[severity] || "#64748b";
  return (
    <span style={{ padding: "2px 8px", borderRadius: 4, fontSize: 10, fontWeight: 700, background: `${color}18`, color, textTransform: "uppercase" }}>{severity}</span>
  );
}

function SectionHeader({ title, subtitle, icon, count }: { title: string; subtitle?: string; icon: string; count?: number }) {
  return (
    <div style={{ display: "flex", alignItems: "center", gap: 12, marginBottom: 20 }}>
      <div style={{ width: 36, height: 36, borderRadius: 8, background: "#f59e0b12", border: "1px solid #f59e0b30", display: "flex", alignItems: "center", justifyContent: "center", fontSize: 16 }}>{icon}</div>
      <div>
        <div style={{ fontSize: 15, fontWeight: 700, color: "#f1f5f9", display: "flex", alignItems: "center", gap: 8 }}>
          {title}
          {count !== undefined && <span style={{ padding: "2px 8px", borderRadius: 10, fontSize: 11, background: "#f59e0b18", color: "#f59e0b" }}>{count}</span>}
        </div>
        {subtitle && <div style={{ fontSize: 12, color: "#64748b", marginTop: 2 }}>{subtitle}</div>}
      </div>
    </div>
  );
}

/* ═══════════════════════════════════════════════════════════════════════════
   TAB: SUMMARY
   ═══════════════════════════════════════════════════════════════════════════ */

function SummaryTab({ result }: { result: ProductionGoldResult }) {
  const { summary, overallConfidence, kpis, aggregationFramework, metricValidations, executiveViews, dataQualityMonitors, auditFramework, dependencyValidations, performanceRecs, productionPipeline } = result;

  const prodStats = [
    { label: "Total Intents", value: summary.totalIntents, color: "#f59e0b", icon: "📊" },
    { label: "KPI Definitions", value: kpis.length, color: "#ef4444", icon: "🎯" },
    { label: "Aggregation Configs", value: aggregationFramework.length, color: "#8b5cf6", icon: "∑" },
    { label: "Executive Views", value: executiveViews.length, color: "#3b82f6", icon: "📋" },
    { label: "Metric Validations", value: metricValidations.length, color: "#10b981", icon: "✓" },
    { label: "DQ Monitors", value: dataQualityMonitors.length, color: "#f97316", icon: "🔍" },
    { label: "Audit Entries", value: auditFramework.length, color: "#06b6d4", icon: "📝" },
    { label: "Dep. Validations", value: dependencyValidations.length, color: "#a78bfa", icon: "🔗" },
    { label: "Performance Recs", value: performanceRecs.length, color: "#fbbf24", icon: "⚡" },
    { label: "Pipeline Stages", value: productionPipeline.length, color: "#34d399", icon: "🔄" },
    { label: "Dashboard-Ready", value: summary.dashboardReadyCount, color: "#60a5fa", icon: "📈" },
    { label: "Complex Calcs", value: summary.complexCalculations, color: "#f87171", icon: "🧮" },
  ];

  const categories = Object.entries(summary.byCategory).filter(([, c]) => c > 0) as [GoldMetricCategory, number][];

  const kpiCategories = kpis.reduce<Record<string, number>>((acc, k) => { acc[k.category] = (acc[k.category] || 0) + 1; return acc; }, {});

  return (
    <div style={{ display: "flex", flexDirection: "column", gap: 24 }}>
      {/* Stats grid */}
      <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(155px, 1fr))", gap: 12 }}>
        {prodStats.map((s) => (
          <div key={s.label} style={{ padding: 16, borderRadius: 12, background: "#131620", border: "1px solid #1e293b", display: "flex", flexDirection: "column", gap: 4 }}>
            <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
              <span style={{ fontSize: 14 }}>{s.icon}</span>
              <span style={{ fontSize: 24, fontWeight: 800, color: s.color }}>{s.value}</span>
            </div>
            <div style={{ fontSize: 11, color: "#64748b" }}>{s.label}</div>
          </div>
        ))}
      </div>

      <div style={{ display: "flex", gap: 20, flexWrap: "wrap" }}>
        {/* Confidence ring */}
        <div style={{ flex: "0 0 200px", padding: 24, borderRadius: 12, background: "#131620", border: "1px solid #1e293b", display: "flex", flexDirection: "column", alignItems: "center" }}>
          <svg width={130} height={130} viewBox="0 0 130 130">
            <circle cx={65} cy={65} r={55} fill="none" stroke="#1e293b" strokeWidth={9} />
            <circle cx={65} cy={65} r={55} fill="none" stroke={overallConfidence >= 0.8 ? "#10b981" : overallConfidence >= 0.6 ? "#f59e0b" : "#ef4444"} strokeWidth={9} strokeLinecap="round" strokeDasharray={`${overallConfidence * 345.6} 345.6`} transform="rotate(-90 65 65)" />
            <text x={65} y={58} textAnchor="middle" fill="#f1f5f9" fontSize={26} fontWeight={800}>{Math.round(overallConfidence * 100)}</text>
            <text x={65} y={78} textAnchor="middle" fill="#64748b" fontSize={11}>confidence</text>
          </svg>
          <div style={{ fontSize: 12, color: "#94a3b8", marginTop: 8, textAlign: "center" }}>Production Gold Layer Confidence Score</div>
        </div>

        {/* Category breakdown */}
        <div style={{ flex: 1, minWidth: 280, padding: 20, borderRadius: 12, background: "#131620", border: "1px solid #1e293b" }}>
          <div style={{ fontSize: 13, fontWeight: 600, color: "#94a3b8", marginBottom: 14 }}>Metric Categories Detected</div>
          <div style={{ display: "flex", flexDirection: "column", gap: 8 }}>
            {categories.map(([cat, count]) => (
              <div key={cat} style={{ display: "flex", alignItems: "center", gap: 10 }}>
                <span style={{ fontSize: 15, width: 24, textAlign: "center" }}>{CAT_ICONS[cat]}</span>
                <span style={{ flex: 1, fontSize: 13, color: "#e2e8f0" }}>{CATEGORY_LABELS[cat]}</span>
                <div style={{ width: 120, height: 6, borderRadius: 3, background: "#1e293b", overflow: "hidden" }}>
                  <div style={{ width: `${Math.min((count / Math.max(summary.totalIntents, 1)) * 100, 100)}%`, height: "100%", borderRadius: 3, background: CAT_COLORS[cat] }} />
                </div>
                <span style={{ fontSize: 12, color: CAT_COLORS[cat], fontWeight: 600, width: 28, textAlign: "right" }}>{count}</span>
              </div>
            ))}
          </div>
        </div>

        {/* KPI category distribution */}
        <div style={{ flex: "0 0 220px", padding: 20, borderRadius: 12, background: "#131620", border: "1px solid #1e293b" }}>
          <div style={{ fontSize: 13, fontWeight: 600, color: "#94a3b8", marginBottom: 14 }}>KPI Distribution</div>
          <div style={{ display: "flex", flexDirection: "column", gap: 8 }}>
            {Object.entries(kpiCategories).map(([cat, count]) => {
              const catColors: Record<string, string> = { revenue: "#f59e0b", operational: "#3b82f6", customer: "#10b981", compliance: "#ef4444", growth: "#8b5cf6" };
              return (
                <div key={cat} style={{ display: "flex", alignItems: "center", gap: 8 }}>
                  <div style={{ width: 8, height: 8, borderRadius: "50%", background: catColors[cat] || "#64748b" }} />
                  <span style={{ flex: 1, fontSize: 12, color: "#e2e8f0", textTransform: "capitalize" }}>{cat}</span>
                  <span style={{ fontSize: 12, fontWeight: 700, color: catColors[cat] || "#64748b" }}>{count}</span>
                </div>
              );
            })}
          </div>
        </div>
      </div>

      {/* Production pipeline overview */}
      <div style={{ padding: 20, borderRadius: 12, background: "#131620", border: "1px solid #1e293b" }}>
        <div style={{ fontSize: 13, fontWeight: 600, color: "#94a3b8", marginBottom: 14 }}>Production Pipeline — {productionPipeline.length} Stages</div>
        <div style={{ display: "flex", gap: 6, flexWrap: "wrap" }}>
          {productionPipeline.map((stage, i) => (
            <div key={i} style={{ display: "flex", alignItems: "center", gap: 6 }}>
              <div style={{ padding: "6px 12px", borderRadius: 8, background: "#f59e0b08", border: "1px solid #f59e0b20", fontSize: 11, color: "#fbbf24", fontWeight: 600 }}>
                {stage.stage}
              </div>
              {i < productionPipeline.length - 1 && <span style={{ color: "#334155", fontSize: 14 }}>→</span>}
            </div>
          ))}
        </div>
      </div>

      {/* Warnings */}
      {summary.warnings.length > 0 && (
        <div style={{ padding: 16, borderRadius: 12, background: "#f59e0b08", border: "1px solid #f59e0b30" }}>
          <div style={{ fontSize: 13, fontWeight: 600, color: "#f59e0b", marginBottom: 8 }}>Warnings ({summary.warnings.length})</div>
          {summary.warnings.map((w, i) => (
            <div key={i} style={{ fontSize: 13, color: "#fbbf24", marginBottom: 4, paddingLeft: 20, position: "relative" }}>
              <span style={{ position: "absolute", left: 0 }}>⚠</span> {w}
            </div>
          ))}
        </div>
      )}

      {/* Intent list */}
      <div style={{ padding: 20, borderRadius: 12, background: "#131620", border: "1px solid #1e293b" }}>
        <div style={{ fontSize: 13, fontWeight: 600, color: "#94a3b8", marginBottom: 14 }}>Extracted Gold Intents ({result.intents.length})</div>
        <div style={{ display: "flex", flexDirection: "column", gap: 6, maxHeight: 320, overflow: "auto" }}>
          {result.intents.map((intent) => (
            <div key={intent.id} style={{ display: "flex", alignItems: "center", gap: 10, padding: "8px 12px", borderRadius: 8, background: "#0f1117" }}>
              <span style={{ fontSize: 14 }}>{CAT_ICONS[intent.category]}</span>
              <span style={{ padding: "2px 8px", borderRadius: 4, fontSize: 10, fontWeight: 700, background: `${CAT_COLORS[intent.category]}20`, color: CAT_COLORS[intent.category] }}>{CATEGORY_LABELS[intent.category]}</span>
              <span style={{ flex: 1, fontSize: 13, color: "#e2e8f0" }}>{intent.description}</span>
              <span style={{
                padding: "2px 8px", borderRadius: 4, fontSize: 10, fontWeight: 700,
                background: intent.complexity === "complex" ? "#ef444420" : intent.complexity === "moderate" ? "#f59e0b20" : "#64748b20",
                color: intent.complexity === "complex" ? "#ef4444" : intent.complexity === "moderate" ? "#f59e0b" : "#94a3b8",
              }}>{intent.complexity}</span>
              <span style={{ fontSize: 12, color: "#64748b" }}>{Math.round(intent.confidence * 100)}%</span>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}

/* ═══════════════════════════════════════════════════════════════════════════
   TAB: KPIs
   ═══════════════════════════════════════════════════════════════════════════ */

function KPIsTab({ kpis, copiedId, onCopy, expanded, onToggle }: { kpis: GoldKPISpec[]; copiedId: string | null; onCopy: (code: string, id: string) => void; expanded: string | null; onToggle: (id: string) => void }) {
  const catColors: Record<string, string> = { revenue: "#f59e0b", operational: "#3b82f6", customer: "#10b981", compliance: "#ef4444", growth: "#8b5cf6" };
  const catIcons: Record<string, string> = { revenue: "💰", operational: "⚙", customer: "👥", compliance: "🛡", growth: "📈" };

  return (
    <div style={{ display: "flex", flexDirection: "column", gap: 16 }}>
      <SectionHeader icon="🎯" title="KPI Specifications" subtitle="Production-ready KPI calculations with thresholds, formulas, and Power BI integration" count={kpis.length} />

      {/* KPI summary cards */}
      <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(280px, 1fr))", gap: 12, marginBottom: 8 }}>
        {kpis.map((kpi) => (
          <div key={kpi.id} style={{ padding: 16, borderRadius: 12, background: "#131620", border: `1px solid ${catColors[kpi.category]}30`, cursor: "pointer" }} onClick={() => onToggle(kpi.id)}>
            <div style={{ display: "flex", alignItems: "center", gap: 8, marginBottom: 10 }}>
              <span style={{ fontSize: 16 }}>{catIcons[kpi.category] || "📊"}</span>
              <span style={{ flex: 1, fontSize: 14, fontWeight: 700, color: "#f1f5f9" }}>{kpi.name}</span>
              <span style={{ padding: "2px 8px", borderRadius: 4, fontSize: 10, fontWeight: 700, background: `${catColors[kpi.category]}18`, color: catColors[kpi.category], textTransform: "uppercase" }}>{kpi.category}</span>
            </div>

            <div style={{ fontSize: 12, color: "#94a3b8", fontFamily: "monospace", marginBottom: 10, padding: "6px 10px", borderRadius: 6, background: "#0f1117" }}>{kpi.formula}</div>

            <div style={{ display: "flex", gap: 6, flexWrap: "wrap", marginBottom: 10 }}>
              <span style={{ padding: "2px 8px", borderRadius: 4, fontSize: 10, background: "#f59e0b18", color: "#f59e0b" }}>{kpi.granularity}</span>
              {kpi.powerBIReady && <span style={{ padding: "2px 8px", borderRadius: 4, fontSize: 10, background: "#10b98118", color: "#10b981" }}>Power BI Ready</span>}
            </div>

            {kpi.threshold && (
              <div style={{ display: "flex", gap: 8, fontSize: 11, color: "#64748b" }}>
                <span>Threshold: </span>
                <span style={{ color: "#f59e0b" }}>⚠ {kpi.threshold.direction === "below" ? "<" : ">"} {kpi.threshold.warning}</span>
                <span style={{ color: "#ef4444" }}>🚨 {kpi.threshold.direction === "below" ? "<" : ">"} {kpi.threshold.critical}</span>
              </div>
            )}

            <div style={{ marginTop: 8, display: "flex", gap: 4, flexWrap: "wrap" }}>
              {kpi.silverInputs.map((dep) => (
                <span key={dep} style={{ padding: "2px 6px", borderRadius: 4, fontSize: 9, fontFamily: "monospace", background: "#8b5cf618", color: "#8b5cf6" }}>{dep}</span>
              ))}
            </div>
          </div>
        ))}
      </div>

      {/* Expanded KPI code */}
      {kpis.map((kpi) => expanded === kpi.id && (
        <div key={`code-${kpi.id}`} style={{ borderRadius: 12, background: "#131620", border: `1px solid ${catColors[kpi.category]}40`, overflow: "hidden" }}>
          <div style={{ padding: "12px 20px", borderBottom: "1px solid #1e293b", display: "flex", alignItems: "center", gap: 8 }}>
            <span style={{ fontSize: 14 }}>{catIcons[kpi.category] || "📊"}</span>
            <span style={{ fontSize: 14, fontWeight: 700, color: "#f1f5f9" }}>{kpi.name}</span>
            <span style={{ flex: 1 }} />
            <span style={{ fontSize: 12, color: "#64748b" }}>{kpi.formula}</span>
          </div>
          <CodeBlock code={kpi.code} id={kpi.id} copiedId={copiedId} onCopy={onCopy} accent="#fbbf24" />
        </div>
      ))}
    </div>
  );
}

/* ═══════════════════════════════════════════════════════════════════════════
   TAB: AGGREGATIONS
   ═══════════════════════════════════════════════════════════════════════════ */

function AggregationsTab({ configs, copiedId, onCopy, expanded, onToggle }: { configs: AggregationConfig[]; copiedId: string | null; onCopy: (code: string, id: string) => void; expanded: string | null; onToggle: (id: string) => void }) {
  const typeColors: Record<string, string> = { rollup: "#f59e0b", cube: "#ef4444", window: "#3b82f6", conditional: "#8b5cf6", pivot: "#10b981", running: "#06b6d4" };
  const typeIcons: Record<string, string> = { rollup: "📐", cube: "🧊", window: "🪟", conditional: "❓", pivot: "🔄", running: "📈" };

  return (
    <div style={{ display: "flex", flexDirection: "column", gap: 16 }}>
      <SectionHeader icon="∑" title="Aggregation Framework" subtitle="Multi-granularity rollups, window analytics, running totals, and pivot tables" count={configs.length} />

      {configs.map((cfg) => (
        <div key={cfg.id} style={{ borderRadius: 12, background: "#131620", border: `1px solid ${typeColors[cfg.type] || "#1e293b"}30`, overflow: "hidden" }}>
          <div onClick={() => onToggle(cfg.id)} style={{ padding: "16px 20px", cursor: "pointer", display: "flex", alignItems: "center", gap: 12 }}>
            <span style={{ fontSize: 16, transform: expanded === cfg.id ? "rotate(90deg)" : "rotate(0)", transition: "transform 0.15s" }}>▶</span>
            <span style={{ fontSize: 18 }}>{typeIcons[cfg.type] || "∑"}</span>
            <div style={{ flex: 1 }}>
              <div style={{ fontSize: 14, fontWeight: 700, color: "#f1f5f9" }}>{cfg.name}</div>
              <div style={{ fontSize: 12, color: "#64748b", marginTop: 2 }}>{cfg.description}</div>
            </div>
            <div style={{ display: "flex", gap: 6, alignItems: "center", flexWrap: "wrap" }}>
              <span style={{ padding: "2px 8px", borderRadius: 4, fontSize: 10, fontWeight: 700, background: `${typeColors[cfg.type]}18`, color: typeColors[cfg.type], textTransform: "uppercase" }}>{cfg.type}</span>
              {cfg.materializedView && <span style={{ padding: "2px 8px", borderRadius: 4, fontSize: 10, background: "#10b98118", color: "#10b981" }}>Materialized</span>}
              <span style={{ padding: "2px 8px", borderRadius: 4, fontSize: 10, background: "#1e293b", color: "#94a3b8", fontFamily: "monospace" }}>{cfg.refreshSchedule}</span>
            </div>
          </div>

          {expanded === cfg.id && (
            <>
              <div style={{ padding: "10px 20px", borderTop: "1px solid #1e293b", borderBottom: "1px solid #1e293b", display: "flex", gap: 8, flexWrap: "wrap", alignItems: "center" }}>
                <span style={{ fontSize: 11, color: "#64748b", fontWeight: 600 }}>Granularities:</span>
                {cfg.granularities.map((g) => (
                  <span key={g} style={{ padding: "2px 8px", borderRadius: 4, fontSize: 10, background: "#f59e0b12", color: "#f59e0b" }}>{g}</span>
                ))}
              </div>
              <CodeBlock code={cfg.code} id={cfg.id} copiedId={copiedId} onCopy={onCopy} accent="#c4b5fd" />
            </>
          )}
        </div>
      ))}
    </div>
  );
}

/* ═══════════════════════════════════════════════════════════════════════════
   TAB: PRODUCTION PIPELINE
   ═══════════════════════════════════════════════════════════════════════════ */

function PipelineTab({ stages, copiedId, onCopy, expanded, onToggle }: { stages: { stage: string; description: string; code: string }[]; copiedId: string | null; onCopy: (code: string, id: string) => void; expanded: string | null; onToggle: (id: string) => void }) {
  const stageIcons = ["✈", "🎯", "∑", "✓", "📋", "🔍", "📝", "⚡", "📧", "🔄"];

  return (
    <div style={{ display: "flex", flexDirection: "column", gap: 16 }}>
      <SectionHeader icon="🔄" title="Production Pipeline Orchestrator" subtitle="End-to-end Gold layer pipeline — 10 stages executing in dependency order with error handling" count={stages.length} />

      {/* Pipeline visualization */}
      <div style={{ padding: 20, borderRadius: 12, background: "#131620", border: "1px solid #1e293b", display: "flex", gap: 4, flexWrap: "wrap", alignItems: "center" }}>
        {stages.map((s, i) => (
          <div key={i} style={{ display: "flex", alignItems: "center", gap: 4 }}>
            <div style={{
              padding: "8px 14px", borderRadius: 8, fontSize: 11, fontWeight: 600, cursor: "pointer",
              background: expanded === `stage-${i}` ? "#f59e0b18" : "#0f1117",
              border: `1px solid ${expanded === `stage-${i}` ? "#f59e0b" : "#1e293b"}`,
              color: expanded === `stage-${i}` ? "#f59e0b" : "#94a3b8",
            }} onClick={() => onToggle(`stage-${i}`)}>
              {stageIcons[i] || "●"} {s.stage}
            </div>
            {i < stages.length - 1 && <span style={{ color: "#334155", fontSize: 12 }}>→</span>}
          </div>
        ))}
      </div>

      {/* Stage details */}
      {stages.map((s, i) => (
        <div key={i} style={{ borderRadius: 12, background: "#131620", border: "1px solid #1e293b", overflow: "hidden" }}>
          <div onClick={() => onToggle(`stage-${i}`)} style={{ padding: "16px 20px", cursor: "pointer", display: "flex", alignItems: "center", gap: 12 }}>
            <span style={{ fontSize: 16, transform: expanded === `stage-${i}` ? "rotate(90deg)" : "rotate(0)", transition: "transform 0.15s" }}>▶</span>
            <div style={{ width: 28, height: 28, borderRadius: 6, background: "#f59e0b12", border: "1px solid #f59e0b30", display: "flex", alignItems: "center", justifyContent: "center", fontSize: 14 }}>{stageIcons[i] || "●"}</div>
            <div style={{ flex: 1 }}>
              <div style={{ fontSize: 14, fontWeight: 700, color: "#f1f5f9" }}>{s.stage}</div>
              <div style={{ fontSize: 12, color: "#64748b", marginTop: 2 }}>{s.description}</div>
            </div>
            <div style={{ padding: "4px 10px", borderRadius: 6, fontSize: 10, fontWeight: 700, background: "#10b98112", color: "#10b981", border: "1px solid #10b98130" }}>Stage {i + 1}/{stages.length}</div>
          </div>

          {expanded === `stage-${i}` && (
            <CodeBlock code={s.code} id={`stage-${i}`} copiedId={copiedId} onCopy={onCopy} accent="#34d399" />
          )}
        </div>
      ))}
    </div>
  );
}

/* ═══════════════════════════════════════════════════════════════════════════
   TAB: EXECUTIVE VIEWS
   ═══════════════════════════════════════════════════════════════════════════ */

function ExecutiveViewsTab({ views, copiedId, onCopy, expanded, onToggle }: { views: ExecutiveView[]; copiedId: string | null; onCopy: (code: string, id: string) => void; expanded: string | null; onToggle: (id: string) => void }) {
  const viewColors: Record<string, string> = { materialized: "#10b981", standard: "#3b82f6", streaming: "#f59e0b", cached: "#8b5cf6" };
  const platformIcons: Record<string, string> = { "power-bi": "📊", "synapse-serverless": "☁", "databricks-sql": "⚡" };

  return (
    <div style={{ display: "flex", flexDirection: "column", gap: 16 }}>
      <SectionHeader icon="📋" title="Executive Reporting Views" subtitle="Materialized views and Power BI optimized datasets for dashboard consumption" count={views.length} />

      {views.map((v) => (
        <div key={v.id} style={{ borderRadius: 12, background: "#131620", border: `1px solid ${viewColors[v.viewType]}30`, overflow: "hidden" }}>
          <div onClick={() => onToggle(v.id)} style={{ padding: "16px 20px", cursor: "pointer", display: "flex", alignItems: "center", gap: 12 }}>
            <span style={{ fontSize: 16, transform: expanded === v.id ? "rotate(90deg)" : "rotate(0)", transition: "transform 0.15s" }}>▶</span>
            <span style={{ fontSize: 18 }}>{platformIcons[v.targetPlatform] || "📊"}</span>
            <div style={{ flex: 1 }}>
              <div style={{ fontSize: 14, fontWeight: 700, color: "#f1f5f9" }}>{v.name}</div>
              <div style={{ fontSize: 12, color: "#64748b", marginTop: 2 }}>{v.description}</div>
            </div>
            <div style={{ display: "flex", gap: 6, alignItems: "center", flexWrap: "wrap" }}>
              <span style={{ padding: "2px 8px", borderRadius: 4, fontSize: 10, fontWeight: 700, background: `${viewColors[v.viewType]}18`, color: viewColors[v.viewType], textTransform: "uppercase" }}>{v.viewType}</span>
              <span style={{ padding: "2px 8px", borderRadius: 4, fontSize: 10, background: "#1e293b", color: "#94a3b8" }}>{v.targetPlatform}</span>
              <span style={{ padding: "2px 8px", borderRadius: 4, fontSize: 10, background: "#1e293b", color: "#94a3b8", fontFamily: "monospace" }}>{v.refreshSchedule}</span>
            </div>
          </div>

          {expanded === v.id && (
            <>
              {v.zordering.length > 0 && (
                <div style={{ padding: "10px 20px", borderTop: "1px solid #1e293b", borderBottom: "1px solid #1e293b", display: "flex", gap: 8, alignItems: "center" }}>
                  <span style={{ fontSize: 11, color: "#64748b", fontWeight: 600 }}>Z-ORDER:</span>
                  {v.zordering.map((z) => (
                    <span key={z} style={{ padding: "2px 8px", borderRadius: 4, fontSize: 10, fontFamily: "monospace", background: "#f59e0b12", color: "#f59e0b" }}>{z}</span>
                  ))}
                </div>
              )}
              <CodeBlock code={v.code} id={v.id} copiedId={copiedId} onCopy={onCopy} accent="#60a5fa" />
            </>
          )}
        </div>
      ))}
    </div>
  );
}

/* ═══════════════════════════════════════════════════════════════════════════
   TAB: VALIDATION & DQ
   ═══════════════════════════════════════════════════════════════════════════ */

function ValidationDQTab({ validations, monitors, copiedId, onCopy, expanded, onToggle }: { validations: BusinessMetricValidation[]; monitors: GoldDataQualityMonitor[]; copiedId: string | null; onCopy: (code: string, id: string) => void; expanded: string | null; onToggle: (id: string) => void }) {
  const valTypeColors: Record<string, string> = { range: "#f59e0b", trend: "#3b82f6", anomaly: "#ef4444", completeness: "#10b981", freshness: "#8b5cf6" };
  const dqTypeColors: Record<string, string> = { "null-rate": "#ef4444", outlier: "#f59e0b", "trend-break": "#8b5cf6", referential: "#3b82f6", "metric-drift": "#f97316", staleness: "#10b981" };

  return (
    <div style={{ display: "flex", flexDirection: "column", gap: 24 }}>
      {/* Metric Validations */}
      <div>
        <SectionHeader icon="✓" title="Business Metric Validations" subtitle="Range checks, trend analysis, anomaly detection, completeness, and freshness verification" count={validations.length} />

        {validations.map((v) => (
          <div key={v.id} style={{ marginBottom: 12, borderRadius: 12, background: "#131620", border: "1px solid #1e293b", overflow: "hidden" }}>
            <div onClick={() => onToggle(v.id)} style={{ padding: "14px 20px", cursor: "pointer", display: "flex", alignItems: "center", gap: 12 }}>
              <span style={{ fontSize: 14, transform: expanded === v.id ? "rotate(90deg)" : "rotate(0)", transition: "transform 0.15s" }}>▶</span>
              <div style={{ flex: 1 }}>
                <div style={{ fontSize: 14, fontWeight: 700, color: "#f1f5f9" }}>{v.metricName}</div>
                <div style={{ fontSize: 11, color: "#94a3b8", fontFamily: "monospace", marginTop: 4 }}>{v.expression}</div>
              </div>
              <div style={{ display: "flex", gap: 6, alignItems: "center" }}>
                <span style={{ padding: "2px 8px", borderRadius: 4, fontSize: 10, fontWeight: 700, background: `${valTypeColors[v.validationType]}18`, color: valTypeColors[v.validationType], textTransform: "uppercase" }}>{v.validationType}</span>
                <SeverityBadge severity={v.severity} />
                {v.autoRemediation && <span style={{ padding: "2px 8px", borderRadius: 4, fontSize: 10, background: "#10b98118", color: "#10b981" }}>Auto-fix</span>}
              </div>
            </div>
            {expanded === v.id && <CodeBlock code={v.code} id={v.id} copiedId={copiedId} onCopy={onCopy} accent="#fbbf24" />}
          </div>
        ))}
      </div>

      {/* Data Quality Monitors */}
      <div>
        <SectionHeader icon="🔍" title="Data Quality Monitors" subtitle="Null-rate checks, outlier detection, trend-break analysis, referential integrity, and staleness monitoring" count={monitors.length} />

        {monitors.map((m) => (
          <div key={m.id} style={{ marginBottom: 12, borderRadius: 12, background: "#131620", border: "1px solid #1e293b", overflow: "hidden" }}>
            <div onClick={() => onToggle(m.id)} style={{ padding: "14px 20px", cursor: "pointer", display: "flex", alignItems: "center", gap: 12 }}>
              <span style={{ fontSize: 14, transform: expanded === m.id ? "rotate(90deg)" : "rotate(0)", transition: "transform 0.15s" }}>▶</span>
              <div style={{ flex: 1 }}>
                <div style={{ fontSize: 14, fontWeight: 700, color: "#f1f5f9" }}>{m.name}</div>
                <div style={{ fontSize: 11, color: "#94a3b8", fontFamily: "monospace", marginTop: 4 }}>{m.expression}</div>
              </div>
              <div style={{ display: "flex", gap: 6, alignItems: "center" }}>
                <span style={{ padding: "2px 8px", borderRadius: 4, fontSize: 10, fontWeight: 700, background: `${dqTypeColors[m.checkType]}18`, color: dqTypeColors[m.checkType], textTransform: "uppercase" }}>{m.checkType}</span>
                <SeverityBadge severity={m.severity} />
                <span style={{ padding: "2px 8px", borderRadius: 4, fontSize: 10, background: "#1e293b", color: "#94a3b8" }}>{m.alertChannel}</span>
              </div>
            </div>
            {expanded === m.id && <CodeBlock code={m.code} id={m.id} copiedId={copiedId} onCopy={onCopy} accent="#f97316" />}
          </div>
        ))}
      </div>
    </div>
  );
}

/* ═══════════════════════════════════════════════════════════════════════════
   TAB: AUDIT & DEPS
   ═══════════════════════════════════════════════════════════════════════════ */

function AuditDepsTab({ audit, deps, incrementalConfig, copiedId, onCopy, expanded, onToggle }: {
  audit: GoldAuditEntry[];
  deps: DependencyValidation[];
  incrementalConfig: ProductionGoldResult["incrementalConfig"];
  copiedId: string | null;
  onCopy: (code: string, id: string) => void;
  expanded: string | null;
  onToggle: (id: string) => void;
}) {
  const auditTypeColors: Record<string, string> = { lineage: "#f59e0b", "metric-snapshot": "#3b82f6", "refresh-log": "#10b981", "access-log": "#8b5cf6", "change-detection": "#ef4444" };
  const depTypeColors: Record<string, string> = { freshness: "#f59e0b", "schema-match": "#3b82f6", "row-count": "#10b981", "partition-existence": "#8b5cf6", "table-exists": "#06b6d4" };

  return (
    <div style={{ display: "flex", flexDirection: "column", gap: 24 }}>
      {/* Incremental Processing Config */}
      <div>
        <SectionHeader icon="🔁" title="Incremental Processing Configuration" subtitle="Delta MERGE strategy for idempotent Gold layer refresh" />
        <div style={{ borderRadius: 12, background: "#131620", border: "1px solid #1e293b", overflow: "hidden" }}>
          <div style={{ padding: "16px 20px", display: "flex", flexWrap: "wrap", gap: 16, borderBottom: "1px solid #1e293b" }}>
            <div>
              <div style={{ fontSize: 10, color: "#64748b", fontWeight: 600, textTransform: "uppercase", marginBottom: 4 }}>Strategy</div>
              <span style={{ padding: "4px 10px", borderRadius: 6, fontSize: 12, fontWeight: 700, background: "#f59e0b18", color: "#f59e0b" }}>{incrementalConfig.strategy}</span>
            </div>
            <div>
              <div style={{ fontSize: 10, color: "#64748b", fontWeight: 600, textTransform: "uppercase", marginBottom: 4 }}>Merge Keys</div>
              <div style={{ display: "flex", gap: 4 }}>
                {incrementalConfig.mergeKeys.map((k) => (
                  <span key={k} style={{ padding: "4px 8px", borderRadius: 4, fontSize: 11, fontFamily: "monospace", background: "#3b82f618", color: "#3b82f6" }}>{k}</span>
                ))}
              </div>
            </div>
            <div>
              <div style={{ fontSize: 10, color: "#64748b", fontWeight: 600, textTransform: "uppercase", marginBottom: 4 }}>Partition Columns</div>
              <div style={{ display: "flex", gap: 4 }}>
                {incrementalConfig.partitionColumns.map((p) => (
                  <span key={p} style={{ padding: "4px 8px", borderRadius: 4, fontSize: 11, fontFamily: "monospace", background: "#10b98118", color: "#10b981" }}>{p}</span>
                ))}
              </div>
            </div>
            <div>
              <div style={{ fontSize: 10, color: "#64748b", fontWeight: 600, textTransform: "uppercase", marginBottom: 4 }}>Watermark Column</div>
              <span style={{ padding: "4px 8px", borderRadius: 4, fontSize: 11, fontFamily: "monospace", background: "#8b5cf618", color: "#8b5cf6" }}>{incrementalConfig.watermarkColumn}</span>
            </div>
          </div>
          <div style={{ padding: "8px 20px 4px", fontSize: 12, color: "#94a3b8" }}>{incrementalConfig.description}</div>
          <div onClick={() => onToggle("incremental")} style={{ padding: "8px 20px", cursor: "pointer", fontSize: 12, color: "#f59e0b", fontWeight: 600 }}>
            {expanded === "incremental" ? "▼ Hide Code" : "▶ Show Incremental Processing Code"}
          </div>
          {expanded === "incremental" && <CodeBlock code={incrementalConfig.code} id="incremental" copiedId={copiedId} onCopy={onCopy} accent="#34d399" />}
        </div>
      </div>

      {/* Audit Framework */}
      <div>
        <SectionHeader icon="📝" title="Audit Framework" subtitle="Metric lineage, snapshots, refresh logs, and change detection for compliance" count={audit.length} />

        {audit.map((a) => (
          <div key={a.id} style={{ marginBottom: 12, borderRadius: 12, background: "#131620", border: "1px solid #1e293b", overflow: "hidden" }}>
            <div onClick={() => onToggle(a.id)} style={{ padding: "14px 20px", cursor: "pointer", display: "flex", alignItems: "center", gap: 12 }}>
              <span style={{ fontSize: 14, transform: expanded === a.id ? "rotate(90deg)" : "rotate(0)", transition: "transform 0.15s" }}>▶</span>
              <div style={{ flex: 1 }}>
                <div style={{ fontSize: 14, fontWeight: 700, color: "#f1f5f9" }}>{a.name}</div>
                <div style={{ fontSize: 12, color: "#64748b", marginTop: 2 }}>{a.description}</div>
              </div>
              <div style={{ display: "flex", gap: 6, alignItems: "center" }}>
                <span style={{ padding: "2px 8px", borderRadius: 4, fontSize: 10, fontWeight: 700, background: `${auditTypeColors[a.auditType]}18`, color: auditTypeColors[a.auditType], textTransform: "uppercase" }}>{a.auditType}</span>
                <span style={{ padding: "2px 8px", borderRadius: 4, fontSize: 10, background: "#1e293b", color: "#94a3b8" }}>{a.retentionDays}d retention</span>
              </div>
            </div>
            {expanded === a.id && <CodeBlock code={a.code} id={a.id} copiedId={copiedId} onCopy={onCopy} accent="#67e8f9" />}
          </div>
        ))}
      </div>

      {/* Dependency Validations */}
      <div>
        <SectionHeader icon="🔗" title="Dependency Validations" subtitle="Pre-flight checks on upstream Silver tables — freshness gates, row counts, and schema compatibility" count={deps.length} />

        {deps.map((d) => (
          <div key={d.id} style={{ marginBottom: 12, borderRadius: 12, background: "#131620", border: "1px solid #1e293b", overflow: "hidden" }}>
            <div onClick={() => onToggle(d.id)} style={{ padding: "14px 20px", cursor: "pointer", display: "flex", alignItems: "center", gap: 12 }}>
              <span style={{ fontSize: 14, transform: expanded === d.id ? "rotate(90deg)" : "rotate(0)", transition: "transform 0.15s" }}>▶</span>
              <div style={{ flex: 1 }}>
                <div style={{ fontSize: 14, fontWeight: 700, color: "#f1f5f9" }}>{d.name}</div>
                <div style={{ fontSize: 12, color: "#64748b", marginTop: 2 }}>{d.description}</div>
              </div>
              <div style={{ display: "flex", gap: 6, alignItems: "center" }}>
                <span style={{ padding: "2px 8px", borderRadius: 4, fontSize: 10, fontWeight: 700, background: `${depTypeColors[d.checkType]}18`, color: depTypeColors[d.checkType], textTransform: "uppercase" }}>{d.checkType}</span>
                {d.blockOnFailure && <span style={{ padding: "2px 8px", borderRadius: 4, fontSize: 10, background: "#ef444418", color: "#ef4444", fontWeight: 700 }}>BLOCKS</span>}
                <span style={{ padding: "2px 8px", borderRadius: 4, fontSize: 10, fontFamily: "monospace", background: "#1e293b", color: "#94a3b8" }}>{d.upstreamTable}</span>
              </div>
            </div>
            {expanded === d.id && <CodeBlock code={d.code} id={d.id} copiedId={copiedId} onCopy={onCopy} accent="#a78bfa" />}
          </div>
        ))}
      </div>
    </div>
  );
}

/* ═══════════════════════════════════════════════════════════════════════════
   TAB: PERFORMANCE
   ═══════════════════════════════════════════════════════════════════════════ */

function PerformanceTab({ recs, copiedId, onCopy, expanded, onToggle }: { recs: GoldPerformanceRec[]; copiedId: string | null; onCopy: (code: string, id: string) => void; expanded: string | null; onToggle: (id: string) => void }) {
  const typeColors: Record<string, string> = { "z-order": "#f59e0b", "partition-pruning": "#3b82f6", "materialized-view": "#10b981", caching: "#8b5cf6", "bloom-filter": "#ef4444", "liquid-clustering": "#06b6d4" };
  const typeIcons: Record<string, string> = { "z-order": "📐", "partition-pruning": "✂", "materialized-view": "📊", caching: "💾", "bloom-filter": "🌸", "liquid-clustering": "💧" };

  return (
    <div style={{ display: "flex", flexDirection: "column", gap: 16 }}>
      <SectionHeader icon="⚡" title="Performance Optimization" subtitle="Z-ORDER clustering, partition pruning, materialized views, bloom filters, and liquid clustering" count={recs.length} />

      {/* Impact summary */}
      <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(280px, 1fr))", gap: 12 }}>
        {recs.map((r) => (
          <div key={r.id} style={{ padding: 16, borderRadius: 12, background: "#131620", border: `1px solid ${typeColors[r.type]}30`, cursor: "pointer" }} onClick={() => onToggle(r.id)}>
            <div style={{ display: "flex", alignItems: "center", gap: 8, marginBottom: 10 }}>
              <span style={{ fontSize: 18 }}>{typeIcons[r.type] || "⚡"}</span>
              <div style={{ flex: 1 }}>
                <div style={{ fontSize: 14, fontWeight: 700, color: "#f1f5f9" }}>{r.title}</div>
                <div style={{ fontSize: 12, color: "#64748b", marginTop: 2 }}>{r.description}</div>
              </div>
            </div>
            <div style={{ display: "flex", gap: 6, alignItems: "center", marginTop: 8 }}>
              <span style={{ padding: "2px 8px", borderRadius: 4, fontSize: 10, fontWeight: 700, background: `${typeColors[r.type]}18`, color: typeColors[r.type], textTransform: "uppercase" }}>{r.type}</span>
              <span style={{ padding: "4px 10px", borderRadius: 6, fontSize: 11, background: "#10b98112", color: "#10b981", fontWeight: 600 }}>{r.estimatedImpact}</span>
            </div>
          </div>
        ))}
      </div>

      {/* Expanded code */}
      {recs.map((r) => expanded === r.id && (
        <div key={`code-${r.id}`} style={{ borderRadius: 12, background: "#131620", border: `1px solid ${typeColors[r.type]}40`, overflow: "hidden" }}>
          <div style={{ padding: "12px 20px", borderBottom: "1px solid #1e293b", display: "flex", alignItems: "center", gap: 8 }}>
            <span style={{ fontSize: 16 }}>{typeIcons[r.type] || "⚡"}</span>
            <span style={{ fontSize: 14, fontWeight: 700, color: "#f1f5f9" }}>{r.title}</span>
            <span style={{ flex: 1 }} />
            <span style={{ padding: "4px 10px", borderRadius: 6, fontSize: 11, background: "#10b98112", color: "#10b981" }}>{r.estimatedImpact}</span>
          </div>
          <CodeBlock code={r.code} id={r.id} copiedId={copiedId} onCopy={onCopy} accent="#fbbf24" />
        </div>
      ))}
    </div>
  );
}

/* ═══════════════════════════════════════════════════════════════════════════
   TAB: ANALYTICS PIPELINE (original specs tab)
   ═══════════════════════════════════════════════════════════════════════════ */

function SpecsTab({
  specs, expanded, onToggle, copiedId, onCopy, filterCat, onFilter,
}: {
  specs: GoldTransformSpec[];
  expanded: string | null;
  onToggle: (id: string) => void;
  copiedId: string | null;
  onCopy: (code: string, id: string) => void;
  filterCat: GoldMetricCategory | "all";
  onFilter: (c: GoldMetricCategory | "all") => void;
}) {
  const filtered = filterCat === "all" ? specs : specs.filter((s) => s.category === filterCat);
  const usedCats = [...new Set(specs.map((s) => s.category))] as GoldMetricCategory[];

  return (
    <div style={{ display: "flex", flexDirection: "column", gap: 16 }}>
      <SectionHeader icon="📊" title="Analytics Pipeline" subtitle="Generated transformation specs — KPI calculations, business metrics, aggregations, and reporting datasets" count={specs.length} />

      <div style={{ display: "flex", gap: 6, flexWrap: "wrap" }}>
        <button onClick={() => onFilter("all")} style={{
          padding: "5px 12px", borderRadius: 6, border: "1px solid", fontSize: 12, fontWeight: 600, cursor: "pointer",
          background: filterCat === "all" ? "#f59e0b18" : "transparent",
          borderColor: filterCat === "all" ? "#f59e0b" : "#1e293b",
          color: filterCat === "all" ? "#f59e0b" : "#64748b",
        }}>All ({specs.length})</button>
        {usedCats.map((cat) => (
          <button key={cat} onClick={() => onFilter(cat)} style={{
            padding: "5px 12px", borderRadius: 6, border: "1px solid", fontSize: 12, fontWeight: 600, cursor: "pointer",
            background: filterCat === cat ? `${CAT_COLORS[cat]}18` : "transparent",
            borderColor: filterCat === cat ? CAT_COLORS[cat] : "#1e293b",
            color: filterCat === cat ? CAT_COLORS[cat] : "#64748b",
          }}>{CAT_ICONS[cat]} {CATEGORY_LABELS[cat]}</button>
        ))}
      </div>

      {filtered.map((s) => (
        <div key={s.id} style={{ borderRadius: 12, background: "#131620", border: "1px solid #1e293b", overflow: "hidden" }}>
          <div onClick={() => onToggle(s.id)} style={{ padding: "16px 20px", cursor: "pointer", display: "flex", alignItems: "center", gap: 12 }}>
            <span style={{ fontSize: 16, transform: expanded === s.id ? "rotate(90deg)" : "rotate(0)", transition: "transform 0.15s" }}>▶</span>
            <span style={{ fontSize: 16 }}>{CAT_ICONS[s.category]}</span>
            <div style={{ flex: 1 }}>
              <div style={{ fontSize: 14, fontWeight: 600, color: "#f1f5f9", fontFamily: "monospace" }}>{s.name}</div>
              <div style={{ fontSize: 12, color: "#64748b", marginTop: 2 }}>{s.description}</div>
            </div>
            <div style={{ display: "flex", gap: 6, alignItems: "center" }}>
              {s.dashboardReady && <span style={{ padding: "2px 8px", borderRadius: 4, fontSize: 10, fontWeight: 700, background: "#10b98118", color: "#10b981" }}>Dashboard</span>}
              <span style={{ padding: "2px 8px", borderRadius: 4, fontSize: 10, fontWeight: 600, background: "#f59e0b18", color: "#f59e0b" }}>{s.granularity}</span>
              <span style={{ padding: "2px 8px", borderRadius: 4, fontSize: 10, fontWeight: 600, background: "#818cf818", color: "#818cf8" }}>{s.language}</span>
            </div>
          </div>

          {expanded === s.id && (
            <div style={{ borderTop: "1px solid #1e293b" }}>
              {s.silverDependencies.length > 0 && (
                <div style={{ padding: "10px 20px", borderBottom: "1px solid #1e293b10", display: "flex", gap: 6, flexWrap: "wrap", alignItems: "center" }}>
                  <span style={{ fontSize: 11, color: "#64748b", fontWeight: 600 }}>Silver deps:</span>
                  {s.silverDependencies.map((d) => (
                    <span key={d} style={{ padding: "2px 8px", borderRadius: 4, fontSize: 10, background: "#8b5cf618", color: "#8b5cf6", fontFamily: "monospace" }}>{d}</span>
                  ))}
                </div>
              )}

              {s.outputSchema.length > 0 && (
                <div style={{ padding: "10px 20px", borderBottom: "1px solid #1e293b10" }}>
                  <div style={{ fontSize: 11, color: "#64748b", fontWeight: 600, marginBottom: 6 }}>Output Schema:</div>
                  <div style={{ display: "flex", gap: 4, flexWrap: "wrap" }}>
                    {s.outputSchema.map((f) => (
                      <span key={f.name} title={`${f.type} — ${f.description}`} style={{
                        padding: "3px 8px", borderRadius: 4, fontSize: 10, fontFamily: "monospace",
                        background: f.isMeasure ? "#f59e0b12" : "#3b82f612",
                        color: f.isMeasure ? "#f59e0b" : "#3b82f6",
                        border: `1px solid ${f.isMeasure ? "#f59e0b20" : "#3b82f620"}`,
                      }}>
                        {f.isMeasure ? "Σ " : "⊞ "}{f.name}
                      </span>
                    ))}
                  </div>
                </div>
              )}

              <CodeBlock code={s.code} id={s.id} copiedId={copiedId} onCopy={onCopy} />
            </div>
          )}
        </div>
      ))}
    </div>
  );
}

/* ═══════════════════════════════════════════════════════════════════════════
   TAB: DEPENDENCY GRAPH
   ═══════════════════════════════════════════════════════════════════════════ */

function DependencyTab({ graph }: { graph: { nodes: DependencyNode[]; links: DependencyLink[] } }) {
  const layerColors: Record<string, string> = { bronze: "#cd7f32", silver: "#c0c0c0", gold: "#f59e0b", external: "#64748b" };
  const relColors: Record<string, string> = { reads: "#3b82f6", aggregates: "#f59e0b", joins: "#10b981", filters: "#8b5cf6", unions: "#06b6d4" };

  const silverNodes = graph.nodes.filter((n) => n.layer === "silver");
  const goldNodes = graph.nodes.filter((n) => n.layer === "gold");
  const extNodes = graph.nodes.filter((n) => n.layer === "external" || n.layer === "bronze");

  return (
    <div style={{ display: "flex", flexDirection: "column", gap: 20 }}>
      <SectionHeader icon="🔗" title="Dependency Graph" subtitle="Visual DAG showing data flow from Silver sources through Gold transformations" count={graph.nodes.length} />

      {/* Legend */}
      <div style={{ display: "flex", gap: 16, flexWrap: "wrap" }}>
        {Object.entries(layerColors).map(([layer, color]) => (
          <div key={layer} style={{ display: "flex", alignItems: "center", gap: 6 }}>
            <div style={{ width: 12, height: 12, borderRadius: 3, background: color }} />
            <span style={{ fontSize: 12, color: "#94a3b8", textTransform: "capitalize" }}>{layer}</span>
          </div>
        ))}
        <div style={{ borderLeft: "1px solid #1e293b", paddingLeft: 16, display: "flex", gap: 12 }}>
          {Object.entries(relColors).map(([rel, color]) => (
            <div key={rel} style={{ display: "flex", alignItems: "center", gap: 6 }}>
              <div style={{ width: 20, height: 2, background: color }} />
              <span style={{ fontSize: 12, color: "#94a3b8", textTransform: "capitalize" }}>{rel}</span>
            </div>
          ))}
        </div>
      </div>

      {/* Visual graph */}
      <div style={{ padding: 24, borderRadius: 12, background: "#131620", border: "1px solid #1e293b", minHeight: 400 }}>
        <svg width="100%" height={Math.max(400, Math.max(silverNodes.length, goldNodes.length) * 70 + 80)} viewBox={`0 0 900 ${Math.max(400, Math.max(silverNodes.length, goldNodes.length) * 70 + 80)}`}>
          {extNodes.length > 0 && <text x={80} y={24} fill="#64748b" fontSize={11} fontWeight={600} textAnchor="middle">EXTERNAL</text>}
          <text x={300} y={24} fill="#c0c0c0" fontSize={11} fontWeight={600} textAnchor="middle">SILVER</text>
          <text x={580} y={24} fill="#f59e0b" fontSize={11} fontWeight={600} textAnchor="middle">GOLD</text>

          {graph.links.map((link, i) => {
            const fromNode = graph.nodes.find((n) => n.id === link.from);
            const toNode = graph.nodes.find((n) => n.id === link.to);
            if (!fromNode || !toNode) return null;

            const fromList = fromNode.layer === "silver" ? silverNodes : extNodes;
            const toList = toNode.layer === "gold" ? goldNodes : silverNodes;
            const fromIdx = fromList.indexOf(fromNode);
            const toIdx = toList.indexOf(toNode);

            const fx = fromNode.layer === "silver" ? 400 : 180;
            const tx = toNode.layer === "gold" ? 480 : 400;
            const fy = 50 + fromIdx * 65;
            const ty = 50 + toIdx * 65;

            return (
              <g key={i}>
                <line x1={fx} y1={fy + 20} x2={tx} y2={ty + 20} stroke={relColors[link.relationship] || "#475569"} strokeWidth={1.5} strokeDasharray={link.relationship === "filters" ? "4 3" : "none"} opacity={0.6} />
                <polygon points={`${tx - 6},${ty + 15} ${tx - 6},${ty + 25} ${tx},${ty + 20}`} fill={relColors[link.relationship] || "#475569"} opacity={0.6} />
              </g>
            );
          })}

          {extNodes.map((n, i) => (
            <g key={n.id} transform={`translate(20, ${50 + i * 65})`}>
              <rect width={160} height={40} rx={8} fill="#64748b18" stroke="#64748b40" strokeWidth={1} />
              <text x={80} y={24} fill="#94a3b8" fontSize={11} textAnchor="middle" fontFamily="monospace">{n.name.slice(0, 20)}</text>
            </g>
          ))}

          {silverNodes.map((n, i) => (
            <g key={n.id} transform={`translate(200, ${50 + i * 65})`}>
              <rect width={200} height={40} rx={8} fill="#c0c0c010" stroke="#c0c0c040" strokeWidth={1.5} />
              <circle cx={16} cy={20} r={5} fill="#c0c0c0" />
              <text x={100} y={24} fill="#e2e8f0" fontSize={11} textAnchor="middle" fontFamily="monospace">{n.name.slice(0, 24)}</text>
            </g>
          ))}

          {goldNodes.map((n, i) => (
            <g key={n.id} transform={`translate(480, ${50 + i * 65})`}>
              <rect width={240} height={40} rx={8} fill="#f59e0b10" stroke="#f59e0b40" strokeWidth={1.5} />
              <circle cx={16} cy={20} r={5} fill="#f59e0b" />
              <text x={120} y={24} fill="#fbbf24" fontSize={11} textAnchor="middle" fontFamily="monospace" fontWeight={600}>{n.name.slice(0, 28)}</text>
            </g>
          ))}
        </svg>
      </div>

      {/* Links table */}
      <div style={{ borderRadius: 12, background: "#131620", border: "1px solid #1e293b", overflow: "hidden" }}>
        <div style={{ padding: "12px 16px", borderBottom: "1px solid #1e293b", fontSize: 13, fontWeight: 600, color: "#94a3b8" }}>
          Dependency Links ({graph.links.length})
        </div>
        <div style={{ maxHeight: 200, overflow: "auto" }}>
          {graph.links.map((l, i) => (
            <div key={i} style={{ display: "flex", alignItems: "center", gap: 8, padding: "8px 16px", borderBottom: "1px solid #1e293b08", fontSize: 12 }}>
              <span style={{ color: "#94a3b8", fontFamily: "monospace" }}>{graph.nodes.find((n) => n.id === l.from)?.name || l.from}</span>
              <span style={{ color: relColors[l.relationship] || "#475569", fontWeight: 600 }}>→ {l.relationship} →</span>
              <span style={{ color: "#f1f5f9", fontFamily: "monospace" }}>{graph.nodes.find((n) => n.id === l.to)?.name || l.to}</span>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}

/* ═══════════════════════════════════════════════════════════════════════════
   TAB: OUTPUT SCHEMA
   ═══════════════════════════════════════════════════════════════════════════ */

function SchemaTab({ specs }: { specs: GoldTransformSpec[] }) {
  const allFields = specs
    .filter((s) => s.outputSchema.length > 0)
    .flatMap((s) => s.outputSchema.map((f) => ({ ...f, source: s.name, granularity: s.granularity })));

  const measures = allFields.filter((f) => f.isMeasure);
  const dimensions = allFields.filter((f) => f.isDimension);

  return (
    <div style={{ display: "flex", flexDirection: "column", gap: 20 }}>
      <SectionHeader icon="📐" title="Output Schema" subtitle="All output fields across Gold datasets — measures, dimensions, and attributes" count={allFields.length} />

      <div style={{ display: "flex", gap: 12 }}>
        {[
          { label: "Total Fields", value: allFields.length, color: "#f59e0b" },
          { label: "Measures", value: measures.length, color: "#ef4444" },
          { label: "Dimensions", value: dimensions.length, color: "#3b82f6" },
          { label: "Datasets", value: specs.filter((s) => s.outputSchema.length > 0).length, color: "#10b981" },
        ].map((s) => (
          <div key={s.label} style={{ flex: 1, padding: 14, borderRadius: 10, background: "#131620", border: "1px solid #1e293b", textAlign: "center" }}>
            <div style={{ fontSize: 22, fontWeight: 800, color: s.color }}>{s.value}</div>
            <div style={{ fontSize: 11, color: "#64748b" }}>{s.label}</div>
          </div>
        ))}
      </div>

      {specs.filter((s) => s.outputSchema.length > 0).map((spec) => (
        <div key={spec.id} style={{ borderRadius: 12, background: "#131620", border: "1px solid #1e293b", overflow: "hidden" }}>
          <div style={{ padding: "12px 16px", borderBottom: "1px solid #1e293b", display: "flex", alignItems: "center", gap: 8 }}>
            <span style={{ fontSize: 14 }}>{CAT_ICONS[spec.category]}</span>
            <span style={{ fontSize: 13, fontWeight: 600, color: "#f1f5f9", fontFamily: "monospace" }}>{spec.name}</span>
            <span style={{ padding: "2px 8px", borderRadius: 4, fontSize: 10, background: "#f59e0b18", color: "#f59e0b" }}>{spec.granularity}</span>
          </div>
          <table style={{ width: "100%", borderCollapse: "collapse", fontSize: 12 }}>
            <thead>
              <tr style={{ borderBottom: "1px solid #1e293b" }}>
                {["Field", "Type", "Role", "Aggregation", "Description"].map((h) => (
                  <th key={h} style={{ padding: "8px 14px", textAlign: "left", color: "#64748b", fontWeight: 600, fontSize: 11, textTransform: "uppercase", letterSpacing: "0.05em" }}>{h}</th>
                ))}
              </tr>
            </thead>
            <tbody>
              {spec.outputSchema.map((f) => (
                <tr key={f.name} style={{ borderBottom: "1px solid #1e293b08" }}>
                  <td style={{ padding: "8px 14px", fontFamily: "monospace", fontWeight: 600, color: f.isMeasure ? "#f59e0b" : "#3b82f6" }}>{f.name}</td>
                  <td style={{ padding: "8px 14px", fontFamily: "monospace", color: "#94a3b8" }}>{f.type}</td>
                  <td style={{ padding: "8px 14px" }}>
                    <span style={{
                      padding: "2px 8px", borderRadius: 4, fontSize: 10, fontWeight: 700,
                      background: f.isMeasure ? "#f59e0b18" : "#3b82f618",
                      color: f.isMeasure ? "#f59e0b" : "#3b82f6",
                    }}>{f.isMeasure ? "Measure" : f.isDimension ? "Dimension" : "Attribute"}</span>
                  </td>
                  <td style={{ padding: "8px 14px", fontFamily: "monospace", color: "#8b5cf6", fontSize: 11 }}>{f.aggregation || "—"}</td>
                  <td style={{ padding: "8px 14px", color: "#94a3b8" }}>{f.description}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      ))}
    </div>
  );
}

/* ═══════════════════════════════════════════════════════════════════════════
   ALERTS TAB
   ═══════════════════════════════════════════════════════════════════════════ */

function AlertsTab({ alerts, copiedId, onCopy }: { alerts: ThresholdAlert[]; copiedId: string | null; onCopy: (c: string, id: string) => void }) {
  const typeColors: Record<string, string> = { warning: "#f59e0b", critical: "#ef4444", recovery: "#10b981" };
  const channelIcons: Record<string, string> = { pagerduty: "🚨", teams: "💬", email: "📧", "log-analytics": "📊" };

  return (
    <div style={{ display: "flex", flexDirection: "column", gap: 14 }}>
      <div style={{ display: "grid", gridTemplateColumns: "repeat(3, 1fr)", gap: 12 }}>
        {(["warning", "critical", "recovery"] as const).map((t) => (
          <div key={t} style={{ padding: 14, borderRadius: 10, background: "#131620", border: `1px solid ${typeColors[t]}30`, textAlign: "center" }}>
            <div style={{ fontSize: 24, fontWeight: 800, color: typeColors[t] }}>{alerts.filter((a) => a.alertType === t).length}</div>
            <div style={{ fontSize: 11, color: "#64748b", textTransform: "capitalize" }}>{t} Alerts</div>
          </div>
        ))}
      </div>
      {alerts.map((a) => (
        <div key={a.id} style={{ borderRadius: 12, background: "#131620", border: `1px solid ${typeColors[a.alertType]}30`, overflow: "hidden" }}>
          <div style={{ padding: "14px 20px", display: "flex", alignItems: "center", gap: 8, borderBottom: "1px solid #1e293b" }}>
            <span style={{ padding: "2px 8px", borderRadius: 4, fontSize: 10, fontWeight: 700, background: `${typeColors[a.alertType]}18`, color: typeColors[a.alertType], textTransform: "uppercase" }}>{a.alertType}</span>
            <span style={{ fontSize: 14, fontWeight: 700, color: "#f1f5f9" }}>{a.kpiName}</span>
            <span style={{ fontSize: 14 }}>{channelIcons[a.channel] || "📡"}</span>
            <span style={{ padding: "2px 8px", borderRadius: 4, fontSize: 10, background: "#1e293b", color: "#94a3b8" }}>{a.channel}</span>
            <button onClick={() => onCopy(a.code, a.id)} style={{ padding: "4px 12px", borderRadius: 6, background: "#1e293b", color: copiedId === a.id ? "#10b981" : "#94a3b8", border: "none", cursor: "pointer", fontSize: 12, fontWeight: 600, marginLeft: "auto" }}>
              {copiedId === a.id ? "Copied!" : "Copy"}
            </button>
          </div>
          <div style={{ padding: "8px 20px", fontSize: 12, color: "#94a3b8", lineHeight: 1.5 }}>{a.description}</div>
          <pre style={{ margin: 0, padding: "12px 20px", fontSize: 11, lineHeight: 1.5, color: "#fbbf24", overflow: "auto", maxHeight: 350, fontFamily: "monospace", whiteSpace: "pre-wrap" }}>{a.code}</pre>
        </div>
      ))}
    </div>
  );
}

/* ═══════════════════════════════════════════════════════════════════════════
   RECONCILIATION TAB
   ═══════════════════════════════════════════════════════════════════════════ */

function ReconciliationTab({ recons, copiedId, onCopy }: { recons: GoldReconciliation[]; copiedId: string | null; onCopy: (c: string, id: string) => void }) {
  const typeColors: Record<string, string> = { count: "#3b82f6", sum: "#10b981", hash: "#8b5cf6", freshness: "#f59e0b" };

  return (
    <div style={{ display: "flex", flexDirection: "column", gap: 14 }}>
      <div style={{ display: "grid", gridTemplateColumns: "repeat(4, 1fr)", gap: 12 }}>
        {(["count", "sum", "hash", "freshness"] as const).map((t) => (
          <div key={t} style={{ padding: 14, borderRadius: 10, background: "#131620", border: `1px solid ${typeColors[t]}30`, textAlign: "center" }}>
            <div style={{ fontSize: 22, fontWeight: 800, color: typeColors[t] }}>{recons.filter((r) => r.reconciliationType === t).length}</div>
            <div style={{ fontSize: 10, color: "#64748b", textTransform: "capitalize" }}>{t}</div>
          </div>
        ))}
      </div>
      {recons.map((r) => (
        <div key={r.id} style={{ borderRadius: 12, background: "#131620", border: `1px solid ${typeColors[r.reconciliationType]}30`, overflow: "hidden" }}>
          <div style={{ padding: "14px 20px", display: "flex", alignItems: "center", gap: 8, borderBottom: "1px solid #1e293b" }}>
            <span style={{ padding: "2px 8px", borderRadius: 4, fontSize: 10, fontWeight: 700, background: `${typeColors[r.reconciliationType]}18`, color: typeColors[r.reconciliationType] }}>{r.reconciliationType}</span>
            <span style={{ fontSize: 14, fontWeight: 700, color: "#f1f5f9" }}>{r.name}</span>
            <span style={{ padding: "2px 8px", borderRadius: 4, fontSize: 10, background: "#1e293b", color: "#94a3b8", marginLeft: "auto" }}>Tolerance: {r.tolerance}%</span>
            <button onClick={() => onCopy(r.code, r.id)} style={{ padding: "4px 12px", borderRadius: 6, background: "#1e293b", color: copiedId === r.id ? "#10b981" : "#94a3b8", border: "none", cursor: "pointer", fontSize: 12, fontWeight: 600 }}>
              {copiedId === r.id ? "Copied!" : "Copy"}
            </button>
          </div>
          <div style={{ padding: "6px 20px", fontSize: 11, color: "#64748b" }}>
            <span style={{ color: "#3b82f6" }}>{r.goldTable}</span> ↔ <span style={{ color: "#10b981" }}>{r.silverTable}</span>
          </div>
          <div style={{ padding: "4px 20px 8px", fontSize: 12, color: "#94a3b8", lineHeight: 1.5 }}>{r.description}</div>
          <pre style={{ margin: 0, padding: "12px 20px", fontSize: 11, lineHeight: 1.5, color: "#60a5fa", overflow: "auto", maxHeight: 350, fontFamily: "monospace", whiteSpace: "pre-wrap" }}>{r.code}</pre>
        </div>
      ))}
    </div>
  );
}

/* ═══════════════════════════════════════════════════════════════════════════
   GOVERNANCE TAB
   ═══════════════════════════════════════════════════════════════════════════ */

function GovernanceTab({ configs, copiedId, onCopy }: { configs: GovernanceConfig[]; copiedId: string | null; onCopy: (c: string, id: string) => void }) {
  const typeColors: Record<string, string> = {
    "table-properties": "#3b82f6",
    "column-tags": "#8b5cf6",
    "row-filter": "#ef4444",
    "column-mask": "#f59e0b",
    "lineage-tag": "#10b981",
  };
  const typeIcons: Record<string, string> = {
    "table-properties": "📋",
    "column-tags": "🏷",
    "row-filter": "🔒",
    "column-mask": "🎭",
    "lineage-tag": "🔗",
  };

  if (configs.length === 0) {
    return (
      <div style={{ textAlign: "center", padding: 60, color: "#64748b" }}>
        <div style={{ fontSize: 32, marginBottom: 12 }}>🏛</div>
        <div style={{ fontSize: 14 }}>Unity Catalog governance is only generated for Azure (aws-to-azure) migrations</div>
      </div>
    );
  }

  return (
    <div style={{ display: "flex", flexDirection: "column", gap: 14 }}>
      <div style={{ display: "grid", gridTemplateColumns: "repeat(5, 1fr)", gap: 10 }}>
        {(["table-properties", "column-tags", "row-filter", "column-mask", "lineage-tag"] as const).map((t) => (
          <div key={t} style={{ padding: 12, borderRadius: 10, background: "#131620", border: `1px solid ${typeColors[t]}30`, textAlign: "center" }}>
            <div style={{ fontSize: 18 }}>{typeIcons[t]}</div>
            <div style={{ fontSize: 18, fontWeight: 800, color: typeColors[t] }}>{configs.filter((c) => c.governanceType === t).length}</div>
            <div style={{ fontSize: 9, color: "#64748b", textTransform: "capitalize" }}>{t.replace(/-/g, " ")}</div>
          </div>
        ))}
      </div>
      {configs.map((c) => (
        <div key={c.id} style={{ borderRadius: 12, background: "#131620", border: `1px solid ${typeColors[c.governanceType]}30`, overflow: "hidden" }}>
          <div style={{ padding: "14px 20px", display: "flex", alignItems: "center", gap: 8, borderBottom: "1px solid #1e293b" }}>
            <span style={{ fontSize: 16 }}>{typeIcons[c.governanceType] || "⚙"}</span>
            <span style={{ padding: "2px 8px", borderRadius: 4, fontSize: 10, fontWeight: 700, background: `${typeColors[c.governanceType]}18`, color: typeColors[c.governanceType] }}>{c.governanceType}</span>
            <span style={{ fontSize: 14, fontWeight: 700, color: "#f1f5f9" }}>{c.name}</span>
            <button onClick={() => onCopy(c.code, c.id)} style={{ padding: "4px 12px", borderRadius: 6, background: "#1e293b", color: copiedId === c.id ? "#10b981" : "#94a3b8", border: "none", cursor: "pointer", fontSize: 12, fontWeight: 600, marginLeft: "auto" }}>
              {copiedId === c.id ? "Copied!" : "Copy"}
            </button>
          </div>
          <div style={{ padding: "8px 20px", fontSize: 12, color: "#94a3b8", lineHeight: 1.5 }}>{c.description}</div>
          <pre style={{ margin: 0, padding: "12px 20px", fontSize: 11, lineHeight: 1.5, color: "#c084fc", overflow: "auto", maxHeight: 400, fontFamily: "monospace", whiteSpace: "pre-wrap" }}>{c.code}</pre>
        </div>
      ))}
    </div>
  );
}
